/**
 * DataHub API
 * DataHub API
 *
 * OpenAPI spec version: 0.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DataHubApi) {
      root.DataHubApi = {};
    }
    root.DataHubApi.GroupMembership = factory(root.DataHubApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GroupMembership model module.
   * @module model/GroupMembership
   * @version 0.0.11
   */

  /**
   * Constructs a new <code>GroupMembership</code>.
   * @alias module:model/GroupMembership
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>GroupMembership</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupMembership} obj Optional instance to populate.
   * @return {module:model/GroupMembership} The populated <code>GroupMembership</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('groupid')) {
        obj['groupid'] = ApiClient.convertToType(data['groupid'], 'String');
      }
      if (data.hasOwnProperty('userid')) {
        obj['userid'] = ApiClient.convertToType(data['userid'], 'String');
      }
      if (data.hasOwnProperty('role')) {
        obj['role'] = ApiClient.convertToType(data['role'], 'String');
      }
    }
    return obj;
  }

  /**
   * The id of the group this entry is part of
   * @member {String} groupid
   */
  exports.prototype['groupid'] = undefined;
  /**
   * The user id of the member
   * @member {String} userid
   */
  exports.prototype['userid'] = undefined;
  /**
   * The role of the user in this group (member, owner)
   * @member {String} role
   */
  exports.prototype['role'] = undefined;



  return exports;
}));


