/**
 * DataHub API
 * DataHub API
 *
 * OpenAPI spec version: 0.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DataHubApi) {
      root.DataHubApi = {};
    }
    root.DataHubApi.PriceInfo = factory(root.DataHubApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PriceInfo model module.
   * @module model/PriceInfo
   * @version 0.0.11
   */

  /**
   * Constructs a new <code>PriceInfo</code>.
   * @alias module:model/PriceInfo
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>PriceInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PriceInfo} obj Optional instance to populate.
   * @return {module:model/PriceInfo} The populated <code>PriceInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Integer');
      }
      if (data.hasOwnProperty('frequency')) {
        obj['frequency'] = ApiClient.convertToType(data['frequency'], 'String');
      }
      if (data.hasOwnProperty('currency')) {
        obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
      }
      if (data.hasOwnProperty('currentPlan')) {
        obj['currentPlan'] = ApiClient.convertToType(data['currentPlan'], 'String');
      }
      if (data.hasOwnProperty('published')) {
        obj['published'] = ApiClient.convertToType(data['published'], 'Boolean');
      }
      if (data.hasOwnProperty('trial')) {
        obj['trial'] = ApiClient.convertToType(data['trial'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * The amount (in cents) of the subscription
   * @member {Integer} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * How often to charge the above
   * @member {String} frequency
   */
  exports.prototype['frequency'] = undefined;
  /**
   * The currency of the subscription amount
   * @member {String} currency
   */
  exports.prototype['currency'] = undefined;
  /**
   * The plan id on Stripe for this repository
   * @member {String} currentPlan
   */
  exports.prototype['currentPlan'] = undefined;
  /**
   * Whether this plan is on stripe or not
   * @member {Boolean} published
   */
  exports.prototype['published'] = undefined;
  /**
   * The amount of days of trial period allowed
   * @member {Integer} trial
   */
  exports.prototype['trial'] = undefined;



  return exports;
}));


