/**
 * DataHub API
 * DataHub API
 *
 * OpenAPI spec version: 0.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SchemeField'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SchemeField'));
  } else {
    // Browser globals (root is window)
    if (!root.DataHubApi) {
      root.DataHubApi = {};
    }
    root.DataHubApi.Scheme = factory(root.DataHubApi.ApiClient, root.DataHubApi.SchemeField);
  }
}(this, function(ApiClient, SchemeField) {
  'use strict';




  /**
   * The Scheme model module.
   * @module model/Scheme
   * @version 0.0.12
   */

  /**
   * Constructs a new <code>Scheme</code>.
   * A schema that could be associated with kv dataset element
   * @alias module:model/Scheme
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Scheme</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Scheme} obj Optional instance to populate.
   * @return {module:model/Scheme} The populated <code>Scheme</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('fields')) {
        obj['fields'] = ApiClient.convertToType(data['fields'], [SchemeField]);
      }
    }
    return obj;
  }

  /**
   * The name of the schema
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The description of the schema
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * fields in this schema
   * @member {Array.<module:model/SchemeField>} fields
   */
  exports.prototype['fields'] = undefined;



  return exports;
}));


