/**
 * DataHub API
 * DataHub API
 *
 * OpenAPI spec version: 0.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DataHubApi) {
      root.DataHubApi = {};
    }
    root.DataHubApi.Subscription = factory(root.DataHubApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Subscription model module.
   * @module model/Subscription
   * @version 0.0.12
   */

  /**
   * Constructs a new <code>Subscription</code>.
   * A subscription is an agreement between a vendor of data and a subscriber of data.
   * @alias module:model/Subscription
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>Subscription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Subscription} obj Optional instance to populate.
   * @return {module:model/Subscription} The populated <code>Subscription</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('usercode')) {
        obj['usercode'] = ApiClient.convertToType(data['usercode'], 'String');
      }
      if (data.hasOwnProperty('repocode')) {
        obj['repocode'] = ApiClient.convertToType(data['repocode'], 'String');
      }
      if (data.hasOwnProperty('plan')) {
        obj['plan'] = ApiClient.convertToType(data['plan'], 'String');
      }
      if (data.hasOwnProperty('startDate')) {
        obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
      }
      if (data.hasOwnProperty('endDate')) {
        obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * The user id who is subscribed
   * @member {String} usercode
   */
  exports.prototype['usercode'] = undefined;
  /**
   * The code of the repo that is to be subscribed to
   * @member {String} repocode
   */
  exports.prototype['repocode'] = undefined;
  /**
   * The payment plan agreement that binds this subscription
   * @member {String} plan
   */
  exports.prototype['plan'] = undefined;
  /**
   * When this subscription started
   * @member {Date} startDate
   */
  exports.prototype['startDate'] = undefined;
  /**
   * When this subscription ends
   * @member {Date} endDate
   */
  exports.prototype['endDate'] = undefined;
  /**
   * The status of this subscription. \"active\" or \"trial\" mean that the user has access to the repository through this subscription
   * @member {String} status
   */
  exports.prototype['status'] = undefined;



  return exports;
}));


