/**
 * Mimir DataHub API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BlockId'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/BlockId'));
  } else {
    // Browser globals (root is window)
    if (!root.MimirDataHubApi) {
      root.MimirDataHubApi = {};
    }
    root.MimirDataHubApi.BlockApi = factory(root.MimirDataHubApi.ApiClient, root.MimirDataHubApi.BlockId);
  }
}(this, function(ApiClient, BlockId) {
  'use strict';

  /**
   * Block service.
   * @module api/BlockApi
   * @version 0.0.7
   */

  /**
   * Constructs a new BlockApi. 
   * @alias module:api/BlockApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the elementsUserIdDataSetReleaseElementPost operation.
     * @callback module:api/BlockApi~elementsUserIdDataSetReleaseElementPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BlockId} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a data block to an element
     * Create a new block aganst an element
     * @param {String} userId The id of the user that this dataset is associated with
     * @param {String} dataSet The id of the data set
     * @param {String} release The id of the release
     * @param {String} element The id of the element
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiKey The user api key
     * @param {module:api/BlockApi~elementsUserIdDataSetReleaseElementPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BlockId}
     */
    this.elementsUserIdDataSetReleaseElementPost = function(userId, dataSet, release, element, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'userId' is set
      if (userId == undefined || userId == null) {
        throw "Missing the required parameter 'userId' when calling elementsUserIdDataSetReleaseElementPost";
      }

      // verify the required parameter 'dataSet' is set
      if (dataSet == undefined || dataSet == null) {
        throw "Missing the required parameter 'dataSet' when calling elementsUserIdDataSetReleaseElementPost";
      }

      // verify the required parameter 'release' is set
      if (release == undefined || release == null) {
        throw "Missing the required parameter 'release' when calling elementsUserIdDataSetReleaseElementPost";
      }

      // verify the required parameter 'element' is set
      if (element == undefined || element == null) {
        throw "Missing the required parameter 'element' when calling elementsUserIdDataSetReleaseElementPost";
      }


      var pathParams = {
        'userId': userId,
        'dataSet': dataSet,
        'release': release,
        'element': element
      };
      var queryParams = {
      };
      var headerParams = {
        'api_key': opts['apiKey']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = BlockId;

      return this.apiClient.callApi(
        '/elements/{userId}/{dataSet}/{release}/{element}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
