/**
 * DataHub API
 * DataHub API
 *
 * OpenAPI spec version: 0.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GeneralStatus', 'model/DataSetRelease'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/GeneralStatus'), require('../model/DataSetRelease'));
  } else {
    // Browser globals (root is window)
    if (!root.DataHubApi) {
      root.DataHubApi = {};
    }
    root.DataHubApi.ReleaseApi = factory(root.DataHubApi.ApiClient, root.DataHubApi.GeneralStatus, root.DataHubApi.DataSetRelease);
  }
}(this, function(ApiClient, GeneralStatus, DataSetRelease) {
  'use strict';

  /**
   * Release service.
   * @module api/ReleaseApi
   * @version 0.0.11
   */

  /**
   * Constructs a new ReleaseApi. 
   * @alias module:api/ReleaseApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addRelease operation.
     * @callback module:api/ReleaseApi~addReleaseCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GeneralStatus} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new open release
     * This creates a new release in a data set. The release defaults to the open (and therefore unpublished) state. 
     * @param {String} userId The id of the user that this dataset is associated with
     * @param {String} repocode The id of the repository
     * @param {module:model/DataSetRelease} body Release object that defines the element in a data set
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiKey The user api key
     * @param {module:api/ReleaseApi~addReleaseCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GeneralStatus}
     */
    this.addRelease = function(userId, repocode, body, opts, callback) {
      opts = opts || {};
      var postBody = body;

      // verify the required parameter 'userId' is set
      if (userId == undefined || userId == null) {
        throw "Missing the required parameter 'userId' when calling addRelease";
      }

      // verify the required parameter 'repocode' is set
      if (repocode == undefined || repocode == null) {
        throw "Missing the required parameter 'repocode' when calling addRelease";
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw "Missing the required parameter 'body' when calling addRelease";
      }


      var pathParams = {
        'userId': userId,
        'repocode': repocode
      };
      var queryParams = {
      };
      var headerParams = {
        'api_key': opts['apiKey']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = GeneralStatus;

      return this.apiClient.callApi(
        '/releases/{userId}/{repocode}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteRelease operation.
     * @callback module:api/ReleaseApi~deleteReleaseCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GeneralStatus} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete release information
     * This deletes a release 
     * @param {String} apiKey The user api key
     * @param {String} releasecode The id of the release
     * @param {module:api/ReleaseApi~deleteReleaseCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GeneralStatus}
     */
    this.deleteRelease = function(apiKey, releasecode, callback) {
      var postBody = null;

      // verify the required parameter 'apiKey' is set
      if (apiKey == undefined || apiKey == null) {
        throw "Missing the required parameter 'apiKey' when calling deleteRelease";
      }

      // verify the required parameter 'releasecode' is set
      if (releasecode == undefined || releasecode == null) {
        throw "Missing the required parameter 'releasecode' when calling deleteRelease";
      }


      var pathParams = {
        'releasecode': releasecode
      };
      var queryParams = {
      };
      var headerParams = {
        'api_key': apiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = GeneralStatus;

      return this.apiClient.callApi(
        '/release/{releasecode}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getRelease operation.
     * @callback module:api/ReleaseApi~getReleaseCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DataSetRelease} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get release information
     * This returns information about a release 
     * @param {String} apiKey The user api key
     * @param {String} releasecode The id of the release
     * @param {module:api/ReleaseApi~getReleaseCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DataSetRelease}
     */
    this.getRelease = function(apiKey, releasecode, callback) {
      var postBody = null;

      // verify the required parameter 'apiKey' is set
      if (apiKey == undefined || apiKey == null) {
        throw "Missing the required parameter 'apiKey' when calling getRelease";
      }

      // verify the required parameter 'releasecode' is set
      if (releasecode == undefined || releasecode == null) {
        throw "Missing the required parameter 'releasecode' when calling getRelease";
      }


      var pathParams = {
        'releasecode': releasecode
      };
      var queryParams = {
      };
      var headerParams = {
        'api_key': apiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = DataSetRelease;

      return this.apiClient.callApi(
        '/release/{releasecode}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getReleases operation.
     * @callback module:api/ReleaseApi~getReleasesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DataSetRelease>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get releases for a repository
     * Get all releases for a repository (with maybe paging later)
     * @param {String} apiKey The user api key
     * @param {String} userId The id of the user that this dataset is associated with
     * @param {String} repocode The id of the repository
     * @param {module:api/ReleaseApi~getReleasesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DataSetRelease>}
     */
    this.getReleases = function(apiKey, userId, repocode, callback) {
      var postBody = null;

      // verify the required parameter 'apiKey' is set
      if (apiKey == undefined || apiKey == null) {
        throw "Missing the required parameter 'apiKey' when calling getReleases";
      }

      // verify the required parameter 'userId' is set
      if (userId == undefined || userId == null) {
        throw "Missing the required parameter 'userId' when calling getReleases";
      }

      // verify the required parameter 'repocode' is set
      if (repocode == undefined || repocode == null) {
        throw "Missing the required parameter 'repocode' when calling getReleases";
      }


      var pathParams = {
        'userId': userId,
        'repocode': repocode
      };
      var queryParams = {
      };
      var headerParams = {
        'api_key': apiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [DataSetRelease];

      return this.apiClient.callApi(
        '/releases/{userId}/{repocode}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the publishRelease operation.
     * @callback module:api/ReleaseApi~publishReleaseCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DataSetRelease} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Publish a release
     * This marks a release as published 
     * @param {String} apiKey The user api key
     * @param {String} releasecode The id of the release
     * @param {module:api/ReleaseApi~publishReleaseCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DataSetRelease}
     */
    this.publishRelease = function(apiKey, releasecode, callback) {
      var postBody = null;

      // verify the required parameter 'apiKey' is set
      if (apiKey == undefined || apiKey == null) {
        throw "Missing the required parameter 'apiKey' when calling publishRelease";
      }

      // verify the required parameter 'releasecode' is set
      if (releasecode == undefined || releasecode == null) {
        throw "Missing the required parameter 'releasecode' when calling publishRelease";
      }


      var pathParams = {
        'releasecode': releasecode
      };
      var queryParams = {
      };
      var headerParams = {
        'api_key': apiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = DataSetRelease;

      return this.apiClient.callApi(
        '/release/publish/{releasecode}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
