/**
 * DataHub API
 * DataHub API
 *
 * OpenAPI spec version: 0.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DataHubApi);
  }
}(this, function(expect, DataHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DataHubApi.Repository();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Repository', function() {
    it('should create an instance of Repository', function() {
      // uncomment below and update the code to test Repository
      //var instane = new DataHubApi.Repository();
      //expect(instance).to.be.a(DataHubApi.Repository);
    });

    it('should have the property owner (base name: "owner")', function() {
      // uncomment below and update the code to test the property owner
      //var instane = new DataHubApi.Repository();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new DataHubApi.Repository();
      //expect(instance).to.be();
    });

    it('should have the property repocode (base name: "repocode")', function() {
      // uncomment below and update the code to test the property repocode
      //var instane = new DataHubApi.Repository();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new DataHubApi.Repository();
      //expect(instance).to.be();
    });

    it('should have the property open (base name: "open")', function() {
      // uncomment below and update the code to test the property open
      //var instane = new DataHubApi.Repository();
      //expect(instance).to.be();
    });

    it('should have the property sampleRelease (base name: "sampleRelease")', function() {
      // uncomment below and update the code to test the property sampleRelease
      //var instane = new DataHubApi.Repository();
      //expect(instance).to.be();
    });

    it('should have the property sampleDataSet (base name: "sampleDataSet")', function() {
      // uncomment below and update the code to test the property sampleDataSet
      //var instane = new DataHubApi.Repository();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instane = new DataHubApi.Repository();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instane = new DataHubApi.Repository();
      //expect(instance).to.be();
    });

  });

}));
