/**
 * Mimir DataHub API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DataElement', 'model/DataElementCsvInfo', 'model/DataElementDisplayInfo', 'model/DataSet', 'model/DataSetRelease', 'model/DataSetView', 'model/GeneralError', 'model/GeneralText', 'model/User', 'model/UserProfile', 'model/UserTokens', 'api/AdminApi', 'api/DataApi', 'api/DatasetApi', 'api/ElementApi', 'api/MarketplaceApi', 'api/ReleaseApi', 'api/UserApi', 'api/ViewApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/DataElement'), require('./model/DataElementCsvInfo'), require('./model/DataElementDisplayInfo'), require('./model/DataSet'), require('./model/DataSetRelease'), require('./model/DataSetView'), require('./model/GeneralError'), require('./model/GeneralText'), require('./model/User'), require('./model/UserProfile'), require('./model/UserTokens'), require('./api/AdminApi'), require('./api/DataApi'), require('./api/DatasetApi'), require('./api/ElementApi'), require('./api/MarketplaceApi'), require('./api/ReleaseApi'), require('./api/UserApi'), require('./api/ViewApi'));
  }
}(function(ApiClient, DataElement, DataElementCsvInfo, DataElementDisplayInfo, DataSet, DataSetRelease, DataSetView, GeneralError, GeneralText, User, UserProfile, UserTokens, AdminApi, DataApi, DatasetApi, ElementApi, MarketplaceApi, ReleaseApi, UserApi, ViewApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var MimirDataHubApi = require('index'); // See note below*.
   * var xxxSvc = new MimirDataHubApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new MimirDataHubApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new MimirDataHubApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new MimirDataHubApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.0.9
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The DataElement model constructor.
     * @property {module:model/DataElement}
     */
    DataElement: DataElement,
    /**
     * The DataElementCsvInfo model constructor.
     * @property {module:model/DataElementCsvInfo}
     */
    DataElementCsvInfo: DataElementCsvInfo,
    /**
     * The DataElementDisplayInfo model constructor.
     * @property {module:model/DataElementDisplayInfo}
     */
    DataElementDisplayInfo: DataElementDisplayInfo,
    /**
     * The DataSet model constructor.
     * @property {module:model/DataSet}
     */
    DataSet: DataSet,
    /**
     * The DataSetRelease model constructor.
     * @property {module:model/DataSetRelease}
     */
    DataSetRelease: DataSetRelease,
    /**
     * The DataSetView model constructor.
     * @property {module:model/DataSetView}
     */
    DataSetView: DataSetView,
    /**
     * The GeneralError model constructor.
     * @property {module:model/GeneralError}
     */
    GeneralError: GeneralError,
    /**
     * The GeneralText model constructor.
     * @property {module:model/GeneralText}
     */
    GeneralText: GeneralText,
    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User: User,
    /**
     * The UserProfile model constructor.
     * @property {module:model/UserProfile}
     */
    UserProfile: UserProfile,
    /**
     * The UserTokens model constructor.
     * @property {module:model/UserTokens}
     */
    UserTokens: UserTokens,
    /**
     * The AdminApi service constructor.
     * @property {module:api/AdminApi}
     */
    AdminApi: AdminApi,
    /**
     * The DataApi service constructor.
     * @property {module:api/DataApi}
     */
    DataApi: DataApi,
    /**
     * The DatasetApi service constructor.
     * @property {module:api/DatasetApi}
     */
    DatasetApi: DatasetApi,
    /**
     * The ElementApi service constructor.
     * @property {module:api/ElementApi}
     */
    ElementApi: ElementApi,
    /**
     * The MarketplaceApi service constructor.
     * @property {module:api/MarketplaceApi}
     */
    MarketplaceApi: MarketplaceApi,
    /**
     * The ReleaseApi service constructor.
     * @property {module:api/ReleaseApi}
     */
    ReleaseApi: ReleaseApi,
    /**
     * The UserApi service constructor.
     * @property {module:api/UserApi}
     */
    UserApi: UserApi,
    /**
     * The ViewApi service constructor.
     * @property {module:api/ViewApi}
     */
    ViewApi: ViewApi
  };

  return exports;
}));
